### ISSUE TITLE
Bug: Packages specified in stacks aren't installed in subsystem

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/apx#270]
Stack config file:

```yml
name: Pico
base: ghcr.io/vanilla-os/pico:main
packages:
- htop
pkgmanager: apt
builtin: false
```

Output (post container creation):

```
kbdharun@apx-pico:~$ htop
bash: htop: command not found
kbdharun@apx-pico:~$ 
```
